/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness and database health */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Provision and return the signed-in User's world
         * @description Idempotent. On first sign-in it atomically creates the User, their Journal, and the five seeded categories; on every later call it returns the same world unchanged.
         */
        post: operations["provisionMe"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/entries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List a date's Entries in order */
        get: operations["listEntries"];
        put?: never;
        /** Create an Entry */
        post: operations["createEntry"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a Category or Subcategory
         * @description Creates a category for the signed-in User with the auto-assigned 'tag' icon (editable later in category management). With parentId it creates a Subcategory of that top-level Category; two levels is the maximum. Names are unique per (User, parent).
         */
        post: operations["createCategory"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/months/{month}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * A month's dot structure in one call
         * @description Days that have Entries, each with its category ids in entry order — everything the month grid needs to draw dots. Titles stay out: the selected-day panel fetches its day through /entries.
         */
        get: operations["getMonth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Me: {
            userId: string;
            journalId: string;
            categories: components["schemas"]["Category"][];
        };
        Category: {
            id: string;
            name: string;
            /** @description Hex color; presets map to the category palette. */
            color: string;
            icon: string;
            parentId?: string;
            position: number;
        };
        CreateCategory: {
            name: string;
            /** @description Hex color. Presets come from the category palette; custom values are free per the ratified color decision. Subcategories store their parent's color but always render through the parent. */
            color: string;
            /** @description When present, creates a Subcategory of this Category. */
            parentId?: string;
        };
        CreateEntry: {
            /** @description The Entry date, YYYY-MM-DD. */
            date: string;
            /** @description A top-level Category owned by the signed-in User. */
            categoryId: string;
            /** @description Optional refinement; must be a child of categoryId. */
            subcategoryId?: string;
            /** @description Opaque versioned blob holding the Entry's title and note. The server stores and returns it verbatim and never parses it (ADR-0004); the title requirement is enforced by the client. Capped at 64 KiB. */
            content: string;
        };
        Entry: {
            id: string;
            date: string;
            position: number;
            categoryId: string;
            subcategoryId?: string;
            authorId: string;
            content: string;
        };
        EntryList: {
            entries: components["schemas"]["Entry"][];
        };
        MonthDay: {
            date: string;
            /** @description The day's Entry categories, in entry order. */
            categoryIds: string[];
        };
        MonthDots: {
            days: components["schemas"]["MonthDay"][];
        };
        Health: {
            /** @enum {string} */
            status: "ok";
            /** @description Version read from the app_info migration baseline. */
            schemaVersion: number;
        };
        Error: {
            message: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description API and database are healthy. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
            /** @description The database is unreachable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    provisionMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The signed-in User's provisioned world. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
            /** @description Missing or invalid access token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Provisioning failed. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    listEntries: {
        parameters: {
            query: {
                /** @description The Entry date, YYYY-MM-DD. */
                date: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The date's Entries, ordered by position. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntryList"];
                };
            };
            /** @description Invalid date. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Missing or invalid access token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Listing Entries failed. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    createEntry: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateEntry"];
            };
        };
        responses: {
            /** @description The created Entry, with its assigned position. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Entry"];
                };
            };
            /** @description Invalid date, unknown category, or missing content. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Missing or invalid access token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Creating the Entry failed. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    createCategory: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCategory"];
            };
        };
        responses: {
            /** @description The created Category, positioned after its siblings. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Category"];
                };
            };
            /** @description Invalid name, color, or parent. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Missing or invalid access token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description A sibling with this name already exists. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Creating the category failed. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getMonth: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The month, YYYY-MM. */
                month: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The month's days that have Entries, in date order. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MonthDots"];
                };
            };
            /** @description Invalid month. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Missing or invalid access token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Loading the month failed. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
}
